jobs:
  deployment:
    environment: prod
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: "actions/checkout@v3"
      - name: Install Rust Toolchain
        uses: "actions-rs/toolchain@v1"
        with:
          profile: minimal
          toolchain: stable
      - name: Setup cargo-lambda
        run: pip3 install cargo-lambda
      - name: Build function code
        uses: "actions-rs/cargo@v1"
        with:
          args: build --release --output-format zip
          command: lambda
      - name: Setup Terraform
        uses: "hashicorp/setup-terraform@v2"
      - name: Configure AWS Credentials
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: ap-northeast-1
          aws-secret-access-key: "${{ secrets.AWS_ACCESS_KEY_SECRET }}"
      - name: Deploy Infrastructure
        run: "terraform init -input=false && terraform apply -auto-approve"
name: Deployment
on:
  push:
    branches:
      - main
